name: Build VS Code Extension

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "package"
      - uses: actions/upload-artifact@v4
        with:
          name: cpp-check-lint
          path: cpp-check-lint-*.vsix
